commonfields:
  id: 72cc381d-c606-4f10-8efd-1ba44381a1d9
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.10.13.84405
enabled: true
engineinfo: {}
mainengineinfo: {}
name: Compose_text_for_tts
pswd: ""
runas: DBotWeakRole
runonce: false
script: ""
scripttarget: 0
subtype: python3
tags: []
type: python
