contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 2.0.20
    packID: CrowdStrikeFalconSandbox
    packName: CrowdStrike Falcon Sandbox
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
deprecated: true
description: Deprecated. Use the cs-falcon-sandbox-submit-url command with polling=true
  instead.
id: detonate_url_-_crowdstrike
inputs:
- description: URL to detonate.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
- description: The environment ID to submit the file to. To get all IDs run the crowdstrike-get-environments
    command.
  key: EnvironmentID
  playbookInputQuery: null
  required: false
  value:
    simple: "100"
- description: Polling frequency - how often the polling command should run (minutes).
  key: Interval
  playbookInputQuery: null
  required: false
  value:
    simple: "5"
- description: How much time to wait before a timeout occurs (minutes).
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "30"
- description: |-
    Should the playbook fail due to an unsupported file type?
    use true or false.
  key: dontThrowErrorOnFileDetonation
  playbookInputQuery: null
  required: false
  value:
    simple: "false"
name: Detonate URL - CrowdStrike
outputs:
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
  type: string
- contextPath: File.Malicious
  description: The file malicious description.
  type: unknown
- contextPath: File.Type
  description: File type, for example "PE".
  type: string
- contextPath: File.Size
  description: The file size.
  type: number
- contextPath: File.MD5
  description: The MD5 hash of the file.
  type: string
- contextPath: File.Name
  description: The file name.
  type: string
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
  type: string
- contextPath: File
  description: The file object.
  type: unknown
- contextPath: File.Malicious.Vendor
  description: The vendor that decided the file was malicious.
  type: string
- contextPath: DBotScore
  description: The DBotScore object.
  type: unknown
- contextPath: DBotScore.Indicator
  description: The tested indicator.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7e5790ea-f1c7-4f11-8d48-429dd24f4891
      iscommand: false
      name: ""
      version: -1
    taskid: 7e5790ea-f1c7-4f11-8d48-429dd24f4891
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: VxStream
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Verify there is a valid instance of CrowdStrike enabled.
      id: be76ffb3-369b-4003-888f-59bc9b4ca113
      iscommand: false
      name: Is CrowdStrike enabled?
      type: condition
      version: -1
    taskid: be76ffb3-369b-4003-888f-59bc9b4ca113
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 755a05f3-fba3-45c7-87bb-fad3c2606f93
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 755a05f3-fba3-45c7-87bb-fad3c2606f93
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          accessor: SHA256
          root: File
    separatecontext: false
    skipunavailable: false
    task:
      brand: VxStream
      description: Downloads the PDF report to the War Room.
      id: 4a4fb455-3725-4948-8a5c-98028d2073cf
      iscommand: true
      name: CrowdStrike Scan
      script: VxStream|||crowdstrike-scan
      type: regular
      version: -1
    taskid: 4a4fb455-3725-4948-8a5c-98028d2073cf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      dontThrowErrorOnFileDetonation:
        complex:
          root: inputs.dontThrowErrorOnFileDetonation
      environmentID:
        complex:
          root: inputs.EnvironmentID
      url:
        complex:
          root: inputs.URL
    separatecontext: false
    skipunavailable: false
    task:
      brand: VxStream
      description: Uploads a sample to CrowdStrike.
      id: db9e268a-d1ff-4aa9-83c7-2bb90fa1ccd8
      iscommand: true
      name: CrowdStrike Upload Sample
      script: VxStream|||crowdstrike-submit-url
      type: regular
      version: -1
    taskid: db9e268a-d1ff-4aa9-83c7-2bb90fa1ccd8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether there's a file to detonate.
      id: 8e34e69c-6900-4586-8342-57dc35adee90
      iscommand: false
      name: Is there a URL to detonate?
      type: condition
      version: -1
    taskid: 8e34e69c-6900-4586-8342-57dc35adee90
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        complex:
          accessor: SHA256
          root: File
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: file
      PollingCommandName:
        simple: crowdstrike-scan
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: File(val.state === 'NO_CONTENT').hash
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (Optional) Get the results of the operation.
      id: bda1000b-f890-47a5-8432-681b470ed1b0
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: bda1000b-f890-47a5-8432-681b470ed1b0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: JobID
                root: CrowdStrike
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2f73943a-4e0e-4375-8c46-7ad0d607944f
      iscommand: false
      name: Was a job created ? (A job is not created if the file type is not supported.)
      type: condition
      version: -1
    taskid: 2f73943a-4e0e-4375-8c46-7ad0d607944f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
