contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 4f2d6fbc-6737-4ce9-8254-e3afdf60d55f
inputs: []
name: Phishing_Attack_Test
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5e9706bc-089a-4c57-811b-b929fbff4dc6
      iscommand: false
      name: ""
      version: -1
    taskid: 5e9706bc-089a-4c57-811b-b929fbff4dc6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    scriptarguments:
      getMalwareBazar_automation:
        simple: ${getMalwareBazar_automation}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ff4b361-06b2-401c-86d1-7cc40039ae40
      iscommand: false
      name: elabora lista di dizionari
      script: 9ebdab1b-bc20-4ad0-82a8-08b3c8d4b017
      type: regular
      version: -1
    taskid: 6ff4b361-06b2-401c-86d1-7cc40039ae40
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 260
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76b78a5f-bfd3-49aa-88c4-a047cc5c8b12
      iscommand: false
      name: test
      script: de94d27e-869d-4e47-803a-abbab1190720
      type: regular
      version: -1
    taskid: 76b78a5f-bfd3-49aa-88c4-a047cc5c8b12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -40,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 870,
        "x": -40,
        "y": 50
      }
    }
  }
