contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.4.9
    packID: ML
    packName: Machine Learning
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: 'Train the phishing machine learning model. This playbook should be used
  as job, to run repeatedly, for example every week. '
id: DBot Create Phishing Classifier V2 Job
inputs: []
name: DBot Create Phishing Classifier V2 Job
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3f296bee-5970-4a35-819b-30ace9905ff7
      iscommand: false
      name: ""
      version: -1
    taskid: 3f296bee-5970-4a35-819b-30ace9905ff7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2153861-94b2-4de6-8883-546b3e4dc5b9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: f2153861-94b2-4de6-8883-546b3e4dc5b9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Close the investigation - we want to close the incident if the
        playbook successfully finished.
      id: a0577456-3576-460d-8ede-15c6569f611a
      iscommand: true
      name: Close incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: a0577456-3576-460d-8ede-15c6569f611a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Clear all context data
      id: cd901cee-98fa-416b-8e39-519218a516ea
      iscommand: false
      name: Clean context
      script: DeleteContext
      type: regular
      version: -1
    taskid: cd901cee-98fa-416b-8e39-519218a516ea
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 4cebffbf-fc15-405c-8120-8203f238ca28
      iscommand: false
      name: DBot Create Phishing Classifier V2
      playbookId: DBot Create Phishing Classifier V2
      type: playbook
      version: -1
    taskid: 4cebffbf-fc15-405c-8120-8203f238ca28
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
