contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: fc803e2d-43cf-4864-81e3-d8ee4159536c
inputs: []
name: Testing
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6ebfcba2-61ce-42f7-8b26-77a115146df6
      iscommand: false
      name: ""
      version: -1
    taskid: 6ebfcba2-61ce-42f7-8b26-77a115146df6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ba2cf0c-f93b-4e33-8adb-5f4d7ec104f6
      iscommand: false
      name: Untitled Task
      script: aa1e70fd-ecb9-4d84-8310-225b0c513b48
      type: regular
      version: -1
    taskid: 1ba2cf0c-f93b-4e33-8adb-5f4d7ec104f6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${testingoutput}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 4d20910e-646b-43b7-8a0e-9a671fd3b5c2
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: 4d20910e-646b-43b7-8a0e-9a671fd3b5c2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 400
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 445,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
