contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8dfe12e5-d092-45ca-8eb5-641e415b4dfb
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: expirationStatus:active
    queryEntity: indicators
    results: null
    runFromLastJobTime: true
  required: false
  value: {}
name: Verify Indicator in SIEM
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 660d8a63-afb5-4627-8534-a87541b44ce1
      iscommand: false
      name: ""
      version: -1
    taskid: 660d8a63-afb5-4627-8534-a87541b44ce1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 470,
          "y": 130
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 29aac4f3-9680-4681-8db0-34f684fad83f
      iscommand: false
      name: Untitled Task
      script: 5a866fc7-b31e-443d-8524-a7d15407081c
      type: regular
      version: -1
    taskid: 29aac4f3-9680-4681-8db0-34f684fad83f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 0,
          "y": 460
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${playbookQuery}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: eb704be2-ec05-4d86-8491-a70946759630
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: eb704be2-ec05-4d86-8491-a70946759630
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 0,
          "y": 310
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      dontPopulateFields:
        simple: id,score,investigationIDs
      populateFields:
        simple: value
      query:
        simple: ${playbookQuery}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets a list of indicator objects and the associated indicator outputs
        that match the specified query and filters. The results are returned in a
        structured data file.
      id: 271ffb9b-0a67-406d-87c9-232ce5b39722
      iscommand: false
      name: Untitled Task
      script: 4792970f-ae76-4c75-80b2-24c3bc90dca4
      type: regular
      version: -1
    taskid: 271ffb9b-0a67-406d-87c9-232ce5b39722
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 470,
          "y": 310
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 425,
        "width": 850,
        "x": 0,
        "y": 130
      }
    }
  }
