contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.1.17
    packID: JoeSecurity
    packName: Joe Security
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: The Detonate File using Joe Sandbox Process is designed to streamline
  and enhance the security assessment of files. This automated system accepts a user-submitted
  file, sends it for in-depth analysis using Joe Sandbox technology, and returns comprehensive
  results as attachments to the user. The process is designed to be swift, efficient,
  and secure, providing users with valuable insights into potential threats and vulnerabilities
  within their files.
id: Detonate File - JoeSecurity V2
inputs:
- description: File object of the file to detonate. The File is taken from the context.
  key: File
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: File
- description: The default duration after which to stop polling and to resume the
    playbook (in seconds).
  key: Timeout
  playbookInputQuery: null
  required: false
  value:
    simple: "900"
- description: 'Operating system to run the analysis on (comma-separated). Supported
    values are: w7, w7x64, w7_1, w7_2, w7native, android2, android3, mac1, w7l, w7x64l,
    w10, android4, w7x64native, w7_3, w10native, android5native_1, w7_4, w7_5, w10x64,
    w7x64_hvm, android6, iphone1, w7_sec, macvm, w7_lang_packs, w7x64native_hvm, lnxubuntu1,
    lnxcentos1, android7_nougat (if no input is provided, the default is w10x64_office)'
  key: Systems
  playbookInputQuery: null
  required: false
  value: {}
- description: Comments for the analysis.
  key: Comments
  playbookInputQuery: null
  required: false
  value: {}
- description: 'The resource type to download. Default is html. Supported values are:
    html, lighthtml, executive, pdf, classhtml, xml, lightxml, classxml, clusterxml,
    irxml, json, jsonfixed, lightjson, lightjsonfixed, irjson, irjsonfixed, shoots
    (screenshots), openioc, maec, misp, graphreports, memstrings, binstrings, sample,
    cookbook, bins (dropped files), unpackpe (unpacked PE files), unpack, ida, pcap,
    pcapslim, memdumps, yara'
  key: ReportFileType
  playbookInputQuery: null
  required: false
  value: {}
name: Detonate File - JoeSecurity V2
outputs:
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: Joe.Analysis.ID
  description: Web ID.
  type: string
- contextPath: Joe.Analysis.Status
  description: Analysis Status.
  type: string
- contextPath: Joe.Analysis.Comments
  description: Analysis Comments.
  type: string
- contextPath: Joe.Analysis.Time
  description: Submitted Time.
  type: date
- contextPath: Joe.Analysis.Runs
  description: Sub-Analysis Information.
- contextPath: Joe.Analysis.Result
  description: Analysis Results.
  type: string
- contextPath: Joe.Analysis.Errors
  description: Raised errors during sampling.
- contextPath: Joe.Analysis.Systems
  description: Analysis OS.
- contextPath: Joe.Analysis.MD5
  description: MD5 of analysis sample.
  type: string
- contextPath: Joe.Analysis.SHA1
  description: SHA1 of analysis sample.
  type: string
- contextPath: Joe.Analysis.SHA256
  description: SHA256 of analysis sample.
  type: string
- contextPath: Joe.Analysis.SampleName
  description: Sample Data, could be a file name or URL.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: number
- contextPath: DBotScore.Malicious.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Malicious.Detections
  description: The sub analysis detection statuses.
  type: string
- contextPath: DBotScore.Malicious.SHA1
  description: The SHA1 of the file.
  type: string
- contextPath: InfoFile.Name
  description: FileName.
  type: string
- contextPath: InfoFile.EntryID
  description: The EntryID of the sample.
  type: string
- contextPath: InfoFile.Size
  description: File Size.
  type: number
- contextPath: InfoFile.Type
  description: File type e.g. "PE".
  type: string
- contextPath: InfoFile.Info
  description: Basic information of the file.
  type: string
- contextPath: File.Extension
  description: File Extension.
  type: string
- contextPath: InfoFile
  description: Report file object.
  type: unknown
- contextPath: File
  description: File object.
  type: unknown
- contextPath: Joe.Analysis
  description: Joe Analysis object.
  type: unknown
- contextPath: DBotScore
  description: DBotScore object.
  type: unknown
- contextPath: DBotScore.Malicious
  description: DBotScore Malicious object.
  type: unknown
- contextPath: File.MD5
  description: The MD5 hash of the file.
- contextPath: File.Name
  description: The full file name.
- contextPath: File.SHA1
  description: The SHA1 hash of the file.
- contextPath: File.SHA256
  description: The SHA256 hash of the file.
starttaskid: "0"
system: true
tags:
- Malware
- Sandbox
- Joe Security
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Detonates a file using JoeSecurity
      id: 2a7c3ace-493a-4ad6-8b77-82fb6386532a
      iscommand: false
      name: ""
      version: -1
    taskid: 2a7c3ace-493a-4ad6-8b77-82fb6386532a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      comments:
        complex:
          root: inputs.Comments
      entry_id:
        complex:
          accessor: EntryID
          root: inputs.File
      systems:
        complex:
          root: inputs.Systems
      timeout:
        complex:
          root: inputs.Timeout
    separatecontext: false
    skipunavailable: false
    task:
      brand: JoeSecurityV2
      description: Submit a sample for sandbox analysis.
      id: 67a2b195-eff4-4586-8b58-19df81b12b6b
      iscommand: true
      name: JoeSecurity Upload File
      script: JoeSecurityV2|||joe-submit-sample
      type: regular
      version: -1
    taskid: 67a2b195-eff4-4586-8b58-19df81b12b6b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 710
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        complex:
          root: inputs.ReportFileType
      webid:
        complex:
          accessor: webid
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: JoeAnalysis.status
              operator: isEqualString
              right:
                value:
                  simple: finished
          root: JoeAnalysis
    separatecontext: false
    skipunavailable: false
    task:
      brand: JoeSecurityV2
      description: Download a resource belonging to a report. This can be the full
        report, dropped binaries, etc. See the integration README for the full list
        of supported report types.
      id: a8c79a81-6e1b-49a4-83cf-8f2011d07267
      iscommand: true
      name: JoeSecurity Get Report
      script: JoeSecurityV2|||joe-download-report
      type: regular
      version: -1
    taskid: a8c79a81-6e1b-49a4-83cf-8f2011d07267
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1200
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d718ec42-1f24-4d49-872b-0c5863ac20b0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d718ec42-1f24-4d49-872b-0c5863ac20b0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1370
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: EntryID
                root: inputs.File
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Look for files to detonate
      id: 019840a3-d2dd-4df7-87b2-36e86a1b361a
      iscommand: false
      name: Is there a File to detonate?
      type: condition
      version: -1
    taskid: 019840a3-d2dd-4df7-87b2-36e86a1b361a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": 370
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: JoeSecurityV2
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if integration instance is enabled
      id: 77b76fb8-4a98-4ce5-82ba-4d4a7815ecb6
      iscommand: false
      name: Is JoeSecurity sandbox enabled?
      type: condition
      version: -1
    taskid: 77b76fb8-4a98-4ce5-82ba-4d4a7815ecb6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      webid:
        complex:
          accessor: webid
          root: Joe.Analysis
    separatecontext: false
    skipunavailable: false
    task:
      brand: JoeSecurityV2
      description: Get information about an analysis.
      id: 50a9fe6b-499a-42ba-83d4-a3fb20770666
      iscommand: true
      name: JoeSecurity Get Info
      script: JoeSecurityV2|||joe-analysis-info
      type: regular
      version: -1
    taskid: 50a9fe6b-499a-42ba-83d4-a3fb20770666
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 875
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: JoeAnalysis
      value:
        complex:
          accessor: Analysis
          root: Joe
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: '-'
      id: 483b9786-6057-48a7-85c0-4c6cf9240984
      iscommand: false
      name: Set Context
      script: Set
      type: regular
      version: -1
    taskid: 483b9786-6057-48a7-85c0-4c6cf9240984
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1040
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.File.Type
          operator: match
          right:
            value:
              simple: .*(?:EXE|DLL|PIF|CMD|BAT|COM|SCR|CPL|PDF|DOCX|DOC|DOCM|XLSX|XLS|XLSM|XLSB|PPT|PPX|PPTM|HWP|JTD|RFT|XPI|CRX|EML|MSG|CHM|JS|JSE|VBS|VBE|LNK|JAR|PS1|ZIP|7Z|RAR|ZLIB|ASPX|APS|PNG|JPEG|GIF|HTML|HTM|XHTML|SHTML|WORD)\b
        - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.File.Extension
          operator: match
          right:
            value:
              simple: .*(?:EXE|DLL|PIF|CMD|BAT|COM|SCR|CPL|PDF|DOCX|DOC|DOCM|XLSX|XLS|XLSM|XLSB|PPT|PPX|PPTM|HWP|JTD|RFT|XPI|CRX|EML|MSG|CHM|JS|JSE|VBS|VBE|LNK|JAR|PS1|ZIP|7Z|RAR|ZLIB|ASPX|APS|PNG|JPEG|GIF|HTML|HTM|XHTML|SHTML)\b
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ad0b0e84-9dc2-4d90-8200-938bdca36a7f
      iscommand: false
      name: Is the file type supported?
      type: condition
      version: -1
    taskid: ad0b0e84-9dc2-4d90-8200-938bdca36a7f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_5_#default#": 0.41,
      "6_5_#default#": 0.23,
      "7_5_#default#": 0.24
    },
    "paper": {
      "dimensions": {
        "height": 1375,
        "width": 1005,
        "x": 275,
        "y": 60
      }
    }
  }
