contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 582311c1-fe1c-4836-86e4-308665fd9406
inputs:
- description: ""
  key: chiave
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: valore
  playbookInputQuery: null
  required: false
  value: {}
name: loop_query_NetWitness
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ae9855e9-4401-4919-8f3b-58284a74f65e
      iscommand: false
      name: ""
      version: -1
    taskid: ae9855e9-4401-4919-8f3b-58284a74f65e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      concentratorIP:
        simple: 172.16.201.204
      query:
        simple: select * from chiave = valore
    separatecontext: false
    skipunavailable: false
    task:
      brand: RSA NetWitness Packets and Logs_copy
      description: Performs a query against the meta database
      id: fcbc422f-6978-4e92-82ed-c02de95fdca4
      iscommand: true
      name: query
      script: RSA NetWitness Packets and Logs_copy|||netwitness-query
      type: regular
      version: -1
    taskid: fcbc422f-6978-4e92-82ed-c02de95fdca4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 20,
          "y": 240
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${inputs.chiave_valore}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 455b5136-348e-48c6-8a09-75851d1b2ff9
      iscommand: false
      name: printa
      script: Print
      type: regular
      version: -1
    taskid: 455b5136-348e-48c6-8a09-75851d1b2ff9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 220
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 820,
        "x": 20,
        "y": 50
      }
    }
  }
