contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.0.0
    itemVersion: 1.1.8
    packID: DevSecOps
    packName: DevSecOps
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: A CodeQL Code Analysis Playbook
id: DevSecOps - LGTM - Analysis - SubPB v2
inputs:
- description: Git Platform
  key: Platform
  playbookInputQuery: null
  required: false
  value:
    simple: g
- description: Git Project Organization
  key: Organization
  playbookInputQuery: null
  required: false
  value: {}
- description: Git Repository
  key: Repository
  playbookInputQuery: null
  required: false
  value: {}
- description: LGTM Task ID
  key: LGTM Task ID
  playbookInputQuery: null
  required: false
  value: {}
name: DevSecOps - LGTM - Analysis - SubPB v2
outputs:
- contextPath: LGTM.project_details.languages.grade
  description: The grade of the code for this language.
- contextPath: LGTM.project_details.id
  description: LGTM Project id
- contextPath: LGTM.project_details.name
  description: LGTM Project name
- contextPath: CreatedIndicator
  description: commands.local.cmd.new.indicator.output.indicator
- contextPath: LGTM.code_review_result
  description: LGTM Code Review Results
- contextPath: LGTM.code_review_result.languages
  description: LGTM Code Review Result Languages
- contextPath: LGTM.code_review_result.languages.alerts
  description: LGTM Code Review Result Languages Alerts
- contextPath: LGTM.code_review_result.languages.alerts.query.properties
  description: LGTM Code Review Results Alerts Query Properties
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Start
      id: 9f6a3cdb-248b-4f04-8615-d43b471f721e
      iscommand: false
      name: ""
      version: -1
    taskid: 9f6a3cdb-248b-4f04-8615-d43b471f721e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 510,
          "y": -520
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: code_review_result.languages.new
                root: LGTM
          operator: greaterThan
          right:
            value:
              simple: "0"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "31"
      "yes":
      - "8"
      - "34"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Alerts Found?
      id: c5d3bb57-60d9-4f54-8b3a-1dba7760c9b4
      iscommand: false
      name: Alerts Found?
      type: condition
      version: -1
    taskid: c5d3bb57-60d9-4f54-8b3a-1dba7760c9b4
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": 660
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: alerts.alert.ruleId
                root: LGTM
          operator: endWith
          right:
            value:
              simple: sql-injection
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: SQL-Injection Discovered?
      id: 9354f52e-d52d-48ac-8f89-51393189de3b
      iscommand: false
      name: SQL-Injection Discovered?
      type: condition
      version: -1
    taskid: 9354f52e-d52d-48ac-8f89-51393189de3b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": 895
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      commit:
        simple: ${LGTM.analysis_summary.commit-id}
      language:
        complex:
          accessor: project_details.languages.language
          root: LGTM
      project-id:
        simple: ${LGTM.project_details.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Run analysis of a specific commit
      id: 7ee1a566-2acd-4b8f-80c7-0da66f50408e
      iscommand: true
      name: Run a SQL Injection CodeQL Query Across All Project
      script: '|||lgtm-request-analysis'
      type: regular
      version: -1
    taskid: 7ee1a566-2acd-4b8f-80c7-0da66f50408e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 622.5,
          "y": 1070
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: DevSecOps SAST Alert
      value:
        simple: ${LGTM.code_review_result.languages.alerts.query.properties.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.new.indicator
      id: 69115a59-1ee3-498e-8fa1-61db95e5ecd1
      iscommand: true
      name: Create SAST Alerts
      script: Builtin|||createNewIndicator
      type: regular
      version: -1
    taskid: 69115a59-1ee3-498e-8fa1-61db95e5ecd1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1275
        }
      }
  "17":
    continueonerror: true
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      project-id:
        simple: ${LGTM.project_details.id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get configuration for a project identified by numeric identifier
      id: 8c56e6e9-48a9-47b9-8c26-b5bc6d6b88ef
      iscommand: true
      name: Get The Query Config
      script: '|||lgtm-get-project-config'
      type: regular
      version: -1
    taskid: 8c56e6e9-48a9-47b9-8c26-b5bc6d6b88ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -10,
          "y": 1070
        }
      }
  "20":
    continueonerror: true
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      name:
        simple: ${inputs.Repository}
      org:
        simple: ${inputs.Organization}
      provider:
        simple: g
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get project by URL identifier
      id: 31c7f00b-056b-43c4-89d8-c8a92788b4f5
      iscommand: true
      name: Get LGTM Project ID
      script: '|||lgtm-get-project-by-url-identifier'
      type: regular
      version: -1
    taskid: 31c7f00b-056b-43c4-89d8-c8a92788b4f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": -190
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      devsecopslgtmanalysisstatus:
        simple: ' '
      devsecopslgtmprojectconfig:
        complex:
          accessor: config
          root: LGTM
      devsecopslgtmprojectgrade:
        complex:
          accessor: project_details.languages.grade
          root: LGTM
      devsecopslgtmprojectid:
        simple: ${LGTM.project_details.id}
      devsecopslgtmprojectlanguage:
        complex:
          accessor: project_details.languages.language
          root: LGTM
      devsecopslgtmprojectname:
        simple: ${LGTM.project_details.name}
      devsecopslgtmprojectstatus:
        complex:
          accessor: project_details.languages.status
          root: LGTM
      devsecopslgtmprojecturl:
        simple: ${LGTM.project_details.url}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: dd3162d2-d49b-4a9d-8d06-ff739421f2fc
      iscommand: true
      name: Parse LGTM Project Details
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: dd3162d2-d49b-4a9d-8d06-ff739421f2fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -10,
          "y": 1275
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "31"
    note: false
    quietmode: 0
    scriptarguments:
      autoclose:
        simple: "true"
      direction:
        simple: Both
      type:
        simple: all
    separatecontext: false
    skipunavailable: false
    task:
      brand: SlackV2
      description: Mirrors the investigation between Slack and the Demisto War Room.
      id: 86e3fdd7-3993-4524-8ebc-b79bead845ab
      iscommand: true
      name: Mirror Investigation to Slack
      script: SlackV2|||mirror-investigation
      type: regular
      version: -1
    taskid: 86e3fdd7-3993-4524-8ebc-b79bead845ab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1040,
          "y": 1275
        }
      }
  "26":
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "32"
    note: false
    quietmode: 0
    scriptarguments:
      review-id:
        simple: ${inputs.LGTM Task ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get results of code review
      id: 8e0a022d-22ab-4ce2-8644-9fd339243e96
      iscommand: true
      name: Get LGTM Code Review Details
      script: '|||lgtm-get-code-review'
      type: regular
      version: -1
    taskid: 8e0a022d-22ab-4ce2-8644-9fd339243e96
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 0
        }
      }
  "28":
    continueonerrortype: ""
    id: "28"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      devsecopslgtmanalysisid:
        simple: ${LGTM.code_review_result.id}
      devsecopslgtmanalysislogsurl:
        simple: ${LGTM.code_review_result.results-url}
      devsecopslgtmanalysisprojectid:
        simple: ${LGTM.project_details.id}
      devsecopslgtmanalysisresultsurl:
        simple: ${LGTM.code_review_result.results-url}
      devsecopslgtmanalysisstatus:
        simple: ${LGTM.code_review_result.status}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: f203fce9-aa3f-468e-8487-e4ac81317200
      iscommand: true
      name: Parse LGTM Code Review Details
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: f203fce9-aa3f-468e-8487-e4ac81317200
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 510
        }
      }
  "31":
    continueonerrortype: ""
    id: "31"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook End
      id: 211401da-8e1f-4387-810b-f0ee12b16992
      iscommand: false
      name: Playbook End
      type: title
      version: -1
    taskid: 211401da-8e1f-4387-810b-f0ee12b16992
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 300,
          "y": 1650
        }
      }
  "32":
    continueonerrortype: ""
    id: "32"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "33"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${LGTM.code_review_result.id}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: review-id
      PollingCommandName:
        simple: lgtm-get-code-review
      Timeout:
        simple: "10"
      dt:
        simple: LGTM.code_review_result(val.status!=="success").id
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f07e5ebc-a7ab-4f94-86ab-7646ddf12596
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: f07e5ebc-a7ab-4f94-86ab-7646ddf12596
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 510,
          "y": 160
        }
      }
  "33":
    continueonerrortype: ""
    id: "33"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "28"
    note: false
    quietmode: 0
    scriptarguments:
      review-id:
        simple: ${inputs.LGTM Task ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get results of code review
      id: aaff7ba3-194e-4540-8b8c-3691c37e1dbd
      iscommand: true
      name: Refresh LGTM Code Review Details
      script: '|||lgtm-get-code-review'
      type: regular
      version: -1
    taskid: aaff7ba3-194e-4540-8b8c-3691c37e1dbd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 510,
          "y": 330
        }
      }
  "34":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: SlackV2
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "34"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "31"
      "yes":
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Slack Enabled?
      id: 483d035a-a13f-478c-8097-3abc85642ee6
      iscommand: false
      name: Slack Enabled?
      type: condition
      version: -1
    taskid: 483d035a-a13f-478c-8097-3abc85642ee6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1040,
          "y": 1070
        }
      }
  "35":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: LGTM
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "31"
      "yes":
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: LGTM Enabled?
      id: 23f2c20d-2f39-40b4-8540-1ca3efb36251
      iscommand: false
      name: LGTM Enabled?
      type: condition
      version: -1
    taskid: 23f2c20d-2f39-40b4-8540-1ca3efb36251
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": -380
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2235,
        "width": 1430,
        "x": -10,
        "y": -520
      }
    }
  }
